apiVersion: v1
kind: Pod
metadata:
  name: po-1
spec:
  schedulerName: doslab-gpu-scheduler
  containers:
  - image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel # pytorch/pytorch:1.2-cuda10.0-cudnn7-devel
    name: torch
    command: [ "sh", "-c", "python3 /workspace/pytorch-cifar/main.py" ]
    resources:
       limits:
         doslab.io/gpu-memory: 2048  # 1024MB
         doslab.io/gpu-core: 20
    volumeMounts:
      - mountPath: /kubeshare/library
        name: lib
      - mountPath: /workspace
        name: code
  volumes:
    - name: lib
      hostPath:
        path: /kubeshare/library
        type: Directory
    - name: code
      hostPath:
        path: /root/gpushare/code
        type: Directory
