apiVersion: doslab.io/v1
kind: Task
metadata:
  name: task1
spec: # PodSpec
  containers:
    - name: torch
      image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
      command: ["sh", "-c", "nvidia-smi dmon -d 5"]
      volumeMounts:
        - mountPath: /workspace
          name: code
  volumes:
    - name: code
      hostPath:
        path: /root/gpushare/code
        type: Directory
---
apiVersion: doslab.io/v1
kind: Task
metadata:
  name: task2
spec: # PodSpec
  containers:
    - name: torch
      image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
      command: ["sh", "-c", "nvidia-smi dmon -d 5"]
      volumeMounts:
        - mountPath: /workspace
          name: code
  volumes:
    - name: code
      hostPath:
        path: /root/gpushare/code
        type: Directory
---
apiVersion: doslab.io/v1
kind: Task
metadata:
  name: task3
spec: # PodSpec
  containers:
    - name: torch
      image: pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel
      command: ["sh", "-c", "nvidia-smi dmon -d 5"]
      volumeMounts:
        - mountPath: /workspace
          name: code
  volumes:
    - name: code
      hostPath:
        path: /root/gpushare/code
        type: Directory